import type { Utilisateur } from '@/types/utilisateur';
import type { Commerce, Categorie } from '@/types/commerce';
import type { Commentaire } from '@/types/commentaire';
import type { StatistiquesGlobales } from '@/types/statistiques';

export const mockArtisans: Utilisateur[] = [
  {
    id: 'art-1',
    email: 'amadou.traore@gmail.com',
    nom: 'Traoré',
    prenom: 'Amadou',
    telephone: '+226 70 12 34 56',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/FFD700/000?text=AT',
    estActif: true,
    dateCreation: '2025-03-15T10:00:00Z',
  },
  {
    id: 'art-2',
    email: 'fatimata.sanou@yahoo.fr',
    nom: 'Sanou',
    prenom: 'Fatimata',
    telephone: '+226 75 23 45 67',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/FF69B4/FFF?text=FS',
    estActif: true,
    dateCreation: '2025-04-02T08:30:00Z',
  },
  {
    id: 'art-3',
    email: 'ibrahim.kone@outlook.com',
    nom: 'Koné',
    prenom: 'Ibrahim',
    telephone: '+226 76 34 56 78',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/4169E1/FFF?text=IK',
    estActif: true,
    dateCreation: '2025-02-10T14:00:00Z',
  },
  {
    id: 'art-4',
    email: 'aminata.diallo@gmail.com',
    nom: 'Diallo',
    prenom: 'Aminata',
    telephone: '+226 70 45 67 89',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/32CD32/FFF?text=AD',
    estActif: true,
    dateCreation: '2025-05-20T09:15:00Z',
  },
  {
    id: 'art-5',
    email: 'moussa.ouedraogo@gmail.com',
    nom: 'Ouédraogo',
    prenom: 'Moussa',
    telephone: '+226 77 56 78 90',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/FF4500/FFF?text=MO',
    estActif: true,
    dateCreation: '2025-01-08T11:45:00Z',
  },
  {
    id: 'art-6',
    email: 'aissatou.compaore@orange.bf',
    nom: 'Compaoré',
    prenom: 'Aissatou',
    telephone: '+226 75 67 89 01',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/9932CC/FFF?text=AC',
    estActif: true,
    dateCreation: '2025-06-01T07:00:00Z',
  },
  {
    id: 'art-7',
    email: 'boubacar.sawadogo@gmail.com',
    nom: 'Sawadogo',
    prenom: 'Boubacar',
    telephone: '+226 76 78 90 12',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/1E90FF/FFF?text=BS',
    estActif: true,
    dateCreation: '2025-04-18T16:20:00Z',
  },
  {
    id: 'art-8',
    email: 'rasmata.zongo@yahoo.fr',
    nom: 'Zongo',
    prenom: 'Rasmata',
    telephone: '+226 70 89 01 23',
    role: 'artisan',
    avatar: 'https://placehold.co/100x100/DC143C/FFF?text=RZ',
    estActif: true,
    dateCreation: '2025-03-25T13:00:00Z',
  },
];

export const mockCitoyens: Utilisateur[] = [
  {
    id: 'cit-1',
    email: 'oumarou.bande@gmail.com',
    nom: 'Bandé',
    prenom: 'Oumarou',
    telephone: '+226 70 11 22 33',
    role: 'citoyen',
    avatar: 'https://placehold.co/100x100/808080/FFF?text=OB',
    estActif: true,
    dateCreation: '2025-05-10T08:00:00Z',
  },
  {
    id: 'cit-2',
    email: 'salamatou.nana@outlook.com',
    nom: 'Nana',
    prenom: 'Salamatou',
    telephone: '+226 75 22 33 44',
    role: 'citoyen',
    avatar: 'https://placehold.co/100x100/DDA0DD/000?text=SN',
    estActif: true,
    dateCreation: '2025-06-05T10:30:00Z',
  },
  {
    id: 'cit-3',
    email: 'karim.tapsoba@gmail.com',
    nom: 'Tapsoba',
    prenom: 'Karim',
    telephone: '+226 76 33 44 55',
    role: 'citoyen',
    avatar: 'https://placehold.co/100x100/20B2AA/FFF?text=KT',
    estActif: true,
    dateCreation: '2025-04-22T14:00:00Z',
  },
  {
    id: 'cit-4',
    email: 'adama.sanou@yahoo.fr',
    nom: 'Sanou',
    prenom: 'Adama',
    telephone: '+226 70 44 55 66',
    role: 'citoyen',
    avatar: 'https://placehold.co/100x100/F4A460/000?text=AS',
    estActif: true,
    dateCreation: '2025-03-18T09:00:00Z',
  },
  {
    id: 'cit-5',
    email: 'halidou.dembele@gmail.com',
    nom: 'Dembélé',
    prenom: 'Halidou',
    telephone: '+226 77 55 66 77',
    role: 'citoyen',
    avatar: 'https://placehold.co/100x100/778899/FFF?text=HD',
    estActif: true,
    dateCreation: '2025-05-30T11:00:00Z',
  },
];

export const mockCategories: Categorie[] = [
  { id: 'cat-1', nom: 'Mécanicien', slug: 'mecanicien', icone: 'Wrench', description: 'Réparation de motos et véhicules', nombreCommerces: 3 },
  { id: 'cat-2', nom: 'Couturier', slug: 'couturier', icone: 'Scissors', description: 'Confection et retouche de vêtements', nombreCommerces: 2 },
  { id: 'cat-3', nom: 'Menuisier', slug: 'menuisier', icone: 'Hammer', description: 'Travail du bois et menuiserie', nombreCommerces: 1 },
  { id: 'cat-4', nom: 'Soudeur', slug: 'soudeur', icone: 'Flame', description: 'Soudure et métallerie', nombreCommerces: 1 },
  { id: 'cat-5', nom: 'Électricien', slug: 'electricien', icone: 'Zap', description: 'Installation et réparation électrique', nombreCommerces: 1 },
  { id: 'cat-6', nom: 'Plombier', slug: 'plombier', icone: 'Droplets', description: 'Installation et réparation de plomberie', nombreCommerces: 1 },
  { id: 'cat-7', nom: 'Coiffeur', slug: 'coiffeur', icone: 'Scissors', description: 'Coiffure et soins capillaires', nombreCommerces: 2 },
  { id: 'cat-8', nom: 'Réparateur téléphones', slug: 'reparateur-telephones', icone: 'Smartphone', description: 'Réparation de téléphones et tablettes', nombreCommerces: 1 },
  { id: 'cat-9', nom: 'Frigoriste', slug: 'frigoriste', icone: 'Snowflake', description: 'Climatisation et froid', nombreCommerces: 1 },
  { id: 'cat-10', nom: 'Peintre', slug: 'peintre', icone: 'PaintBucket', description: 'Peinture bâtiment et décoration', nombreCommerces: 1 },
];

export const mockCommerces: Commerce[] = [
  {
    id: 'com-1',
    nom: 'Garage Amadou Moto',
    description: 'Spécialiste en réparation de motos japonaises et chinoises. Pièces détachées disponibles. Service rapide et fiable.',
    categorieId: 'cat-1',
    artisanId: 'art-1',
    adresse: ' Avenue Kwamé Nkrumah, face à la station Total',
    ville: 'Ouagadougou',
    latitude: 12.3714,
    longitude: -1.5197,
    telephone: '+226 70 12 34 56',
    whatsapp: '+226 70 12 34 56',
    email: 'amadou.traore@gmail.com',
    photos: [
      'https://placehold.co/600x400/333/FFF?text=Garage+Amadou+1',
      'https://placehold.co/600x400/333/FFF?text=Garage+Amadou+2',
    ],
    note: 4.7,
    nombreAvis: 23,
    nombreVues: 156,
    nombreAppels: 45,
    nombreClicsWhatsApp: 32,
    estPublic: true,
    dateCreation: '2025-03-15T10:00:00Z',
    dateModification: '2025-06-20T14:30:00Z',
  },
  {
    id: 'com-2',
    nom: 'Atelier Fatimata Couture',
    description: 'Confection de robes, pagne et accessoires sur mesure. Spécialiste en tenues de mariage et cérémonies.',
    categorieId: 'cat-2',
    artisanId: 'art-2',
    adresse: 'Rue de la Révolution, près du Marché Rood Woko',
    ville: 'Ouagadougou',
    latitude: 12.3682,
    longitude: -1.5245,
    telephone: '+226 75 23 45 67',
    whatsapp: '+226 75 23 45 67',
    photos: [
      'https://placehold.co/600x400/FFB6C1/000?text=Atelier+Fatimata+1',
      'https://placehold.co/600x400/FFB6C1/000?text=Atelier+Fatimata+2',
    ],
    note: 4.9,
    nombreAvis: 41,
    nombreVues: 289,
    nombreAppels: 67,
    nombreClicsWhatsApp: 58,
    estPublic: true,
    dateCreation: '2025-04-02T08:30:00Z',
    dateModification: '2025-06-22T09:00:00Z',
  },
  {
    id: 'com-3',
    nom: 'Menuiserie Ibrahim Bois',
    description: 'Fabrication de meubles sur mesure : tables, chaises, portes, fenêtres. Bois local de qualité.',
    categorieId: 'cat-3',
    artisanId: 'art-3',
    adresse: 'Quartier Karpala, route de Bobo',
    ville: 'Ouagadougou',
    latitude: 12.3756,
    longitude: -1.5134,
    telephone: '+226 76 34 56 78',
    photos: [
      'https://placehold.co/600x400/8B4513/FFF?text=Menuiserie+Ibrahim+1',
    ],
    note: 4.3,
    nombreAvis: 12,
    nombreVues: 87,
    nombreAppels: 19,
    nombreClicsWhatsApp: 14,
    estPublic: true,
    dateCreation: '2025-02-10T14:00:00Z',
    dateModification: '2025-06-18T11:00:00Z',
  },
  {
    id: 'com-4',
    nom: 'Souderie Aminata',
    description: 'Soudure professionnelle : grilles, portails, charpentes métalliques, réservoirs. Devis gratuit.',
    categorieId: 'cat-4',
    artisanId: 'art-4',
    adresse: 'Zone industrielle, lot 45',
    ville: 'Ouagadougou',
    latitude: 12.3645,
    longitude: -1.5089,
    telephone: '+226 70 45 67 89',
    whatsapp: '+226 70 45 67 89',
    photos: [
      'https://placehold.co/600x400/4682B4/FFF?text=Souderie+Aminata+1',
      'https://placehold.co/600x400/4682B4/FFF?text=Souderie+Aminata+2',
    ],
    note: 4.5,
    nombreAvis: 18,
    nombreVues: 134,
    nombreAppels: 31,
    nombreClicsWhatsApp: 27,
    estPublic: true,
    dateCreation: '2025-05-20T09:15:00Z',
    dateModification: '2025-06-21T16:00:00Z',
  },
  {
    id: 'com-5',
    nom: 'Électricité Moussa',
    description: 'Installation électrique complète, dépannage, mise aux normes. Domotique et sécurité.',
    categorieId: 'cat-5',
    artisanId: 'art-5',
    adresse: 'Tampouy, face à l\'université Joseph Ki-Zerbo',
    ville: 'Ouagadougou',
    latitude: 12.3798,
    longitude: -1.5276,
    telephone: '+226 77 56 78 90',
    photos: [
      'https://placehold.co/600x400/FFD700/000?text=Electricite+Moussa+1',
    ],
    note: 4.1,
    nombreAvis: 9,
    nombreVues: 67,
    nombreAppels: 15,
    nombreClicsWhatsApp: 11,
    estPublic: true,
    dateCreation: '2025-01-08T11:45:00Z',
    dateModification: '2025-06-19T08:00:00Z',
  },
  {
    id: 'com-6',
    nom: 'Plomberie Aissatou',
    description: 'Installation et réparation de plomberie, robinetterie, fuite d\'eau. Intervention rapide à domicile.',
    categorieId: 'cat-6',
    artisanId: 'art-6',
    adresse: 'Koudougou, quartier Bassinko',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1771,
    longitude: -4.2979,
    telephone: '+226 75 67 89 01',
    whatsapp: '+226 75 67 89 01',
    photos: [
      'https://placehold.co/600x400/00CED1/FFF?text=Plomberie+Aissatou+1',
    ],
    note: 4.6,
    nombreAvis: 14,
    nombreVues: 98,
    nombreAppels: 22,
    nombreClicsWhatsApp: 18,
    estPublic: true,
    dateCreation: '2025-06-01T07:00:00Z',
    dateModification: '2025-06-23T10:00:00Z',
  },
  {
    id: 'com-7',
    nom: 'Salon Coiffure Boubacar',
    description: 'Coupe homme et femme, tresses, tissages, soins capillaires. Ambiance musicale garantie.',
    categorieId: 'cat-7',
    artisanId: 'art-7',
    adresse: 'Bobo-Dioulasso, secteur 12, près du barrage',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1833,
    longitude: -4.2956,
    telephone: '+226 76 78 90 12',
    photos: [
      'https://placehold.co/600x400/FF1493/FFF?text=Salon+Boubacar+1',
      'https://placehold.co/600x400/FF1493/FFF?text=Salon+Boubacar+2',
    ],
    note: 4.8,
    nombreAvis: 35,
    nombreVues: 210,
    nombreAppels: 52,
    nombreClicsWhatsApp: 43,
    estPublic: true,
    dateCreation: '2025-04-18T16:20:00Z',
    dateModification: '2025-06-24T12:00:00Z',
  },
  {
    id: 'com-8',
    nom: 'Réparation Phone Rasmata',
    description: 'Réparation écran cassé, batterie, carte mère. Vente d\'accessoires et coques. Toutes marques.',
    categorieId: 'cat-8',
    artisanId: 'art-8',
    adresse: 'Ouagadougou, Rue du Commerce, centre-ville',
    ville: 'Ouagadougou',
    latitude: 12.3701,
    longitude: -1.5198,
    telephone: '+226 70 89 01 23',
    whatsapp: '+226 70 89 01 23',
    photos: [
      'https://placehold.co/600x400/8A2BE2/FFF?text=Phone+Rasmata+1',
    ],
    note: 4.4,
    nombreAvis: 27,
    nombreVues: 178,
    nombreAppels: 41,
    nombreClicsWhatsApp: 36,
    estPublic: true,
    dateCreation: '2025-03-25T13:00:00Z',
    dateModification: '2025-06-22T17:00:00Z',
  },
  {
    id: 'com-9',
    nom: 'Froid & Clim Amadou',
    description: 'Installation et dépannage climatisation, réfrigérateur, chambre froide. Clientèle professionnelle et particuliers.',
    categorieId: 'cat-9',
    artisanId: 'art-1',
    adresse: 'Bobo-Dioulasso, Falémé, route de Banfora',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1722,
    longitude: -4.3012,
    telephone: '+226 70 12 34 56',
    photos: [
      'https://placehold.co/600x400/ADD8E6/000?text=Froid+Clim+1',
    ],
    note: 3.9,
    nombreAvis: 7,
    nombreVues: 45,
    nombreAppels: 11,
    nombreClicsWhatsApp: 8,
    estPublic: true,
    dateCreation: '2025-05-05T08:00:00Z',
    dateModification: '2025-06-20T10:00:00Z',
  },
  {
    id: 'com-10',
    nom: 'Peinture & Déco Fatimata',
    description: 'Peinture bâtiment, décoration intérieure, faux plaques, conseil couleur. Résultat professionnel.',
    categorieId: 'cat-10',
    artisanId: 'art-2',
    adresse: 'Ouagadougou, Patte d\'Oie, près de la mairie',
    ville: 'Ouagadougou',
    latitude: 12.3622,
    longitude: -1.5156,
    telephone: '+226 75 23 45 67',
    photos: [
      'https://placehold.co/600x400/FFA500/FFF?text=Peinture+Fatimata+1',
    ],
    note: 4.7,
    nombreAvis: 19,
    nombreVues: 143,
    nombreAppels: 28,
    nombreClicsWhatsApp: 22,
    estPublic: true,
    dateCreation: '2025-04-10T09:00:00Z',
    dateModification: '2025-06-23T14:00:00Z',
  },
  {
    id: 'com-11',
    nom: 'Mécanicien Moussa Pro',
    description: 'Réparation moteur, boîte de vitesses, embrayage. Spécialiste Toyota et Peugeot. Pièces d\'origine.',
    categorieId: 'cat-1',
    artisanId: 'art-5',
    adresse: 'Bobo-Dioulasso, secteur 20, près du stade',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1855,
    longitude: -4.2890,
    telephone: '+226 77 56 78 90',
    photos: [
      'https://placehold.co/600x400/A0522D/FFF?text=Mecanicien+Moussa+1',
    ],
    note: 4.2,
    nombreAvis: 15,
    nombreVues: 102,
    nombreAppels: 24,
    nombreClicsWhatsApp: 17,
    estPublic: true,
    dateCreation: '2025-02-20T10:00:00Z',
    dateModification: '2025-06-21T11:00:00Z',
  },
  {
    id: 'com-12',
    nom: 'Couturier Ibrahim Élégance',
    description: 'Costumes sur mesure, chemises, pantalons. Tissus importés et locaux. Livraison possible.',
    categorieId: 'cat-2',
    artisanId: 'art-3',
    adresse: 'Ouagadougou, Zone du Bois, near the university',
    ville: 'Ouagadougou',
    latitude: 12.3745,
    longitude: -1.5301,
    telephone: '+226 76 34 56 78',
    photos: [
      'https://placehold.co/600x400/9370DB/FFF?text=Couturier+Ibrahim+1',
    ],
    note: 4.6,
    nombreAvis: 21,
    nombreVues: 156,
    nombreAppels: 35,
    nombreClicsWhatsApp: 29,
    estPublic: true,
    dateCreation: '2025-03-01T12:00:00Z',
    dateModification: '2025-06-22T15:00:00Z',
  },
  {
    id: 'com-13',
    nom: 'Coiffure Aminata Beauty',
    description: 'Salon de coiffure moderne. Afro, tresses, nattes, soins. Espace enfants disponible.',
    categorieId: 'cat-7',
    artisanId: 'art-4',
    adresse: 'Bobo-Dioulasso, Sarfalao, près du rond-point',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1798,
    longitude: -4.2934,
    telephone: '+226 70 45 67 89',
    whatsapp: '+226 70 45 67 89',
    photos: [
      'https://placehold.co/600x400/FF69B4/FFF?text=Coiffure+Aminata+1',
    ],
    note: 4.8,
    nombreAvis: 38,
    nombreVues: 245,
    nombreAppels: 58,
    nombreClicsWhatsApp: 47,
    estPublic: true,
    dateCreation: '2025-04-05T08:30:00Z',
    dateModification: '2025-06-24T09:00:00Z',
  },
  {
    id: 'com-14',
    nom: 'Peinture Bâtiment Boubacar',
    description: 'Peinture extérieure et intérieure, ragréage, carrelage. Finitions soignées. Devis gratuit.',
    categorieId: 'cat-10',
    artisanId: 'art-7',
    adresse: 'Ouagadougou, Cissin, près de l\'école primaire',
    ville: 'Ouagadougou',
    latitude: 12.3678,
    longitude: -1.5212,
    telephone: '+226 76 78 90 12',
    photos: [
      'https://placehold.co/600x400/DEB887/000?text=Peinture+Boubacar+1',
    ],
    note: 4.0,
    nombreAvis: 11,
    nombreVues: 78,
    nombreAppels: 17,
    nombreClicsWhatsApp: 13,
    estPublic: true,
    dateCreation: '2025-05-12T14:00:00Z',
    dateModification: '2025-06-20T13:00:00Z',
  },
  {
    id: 'com-15',
    nom: 'Frigoriste Aissatou Services',
    description: 'Climatisation résidentielle et commerciale. Maintenance préventive et curative. Garantie 1 an.',
    categorieId: 'cat-9',
    artisanId: 'art-6',
    adresse: 'Bobo-Dioulasso, Accart-Ville, près de la préfecture',
    ville: 'Bobo-Dioulasso',
    latitude: 11.1810,
    longitude: -4.2978,
    telephone: '+226 75 67 89 01',
    photos: [
      'https://placehold.co/600x400/B0E0E6/000?text=Frigoriste+Aissatou+1',
    ],
    note: 4.3,
    nombreAvis: 8,
    nombreVues: 56,
    nombreAppels: 13,
    nombreClicsWhatsApp: 10,
    estPublic: true,
    dateCreation: '2025-06-10T10:00:00Z',
    dateModification: '2025-06-23T16:00:00Z',
  },
];

export const mockCommentaires: Commentaire[] = [
  {
    id: 'com-1',
    texte: 'Excellent travail sur ma moto ! Amadou a réparé le moteur en une journée. Je recommande vivement.',
    note: 5,
    auteurId: 'cit-1',
    commerceId: 'com-1',
    iaScore: 0.92,
    iaResume: 'Client très satisfait de la réparation moteur. Travail rapide et de qualité.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-01T14:00:00Z',
  },
  {
    id: 'com-2',
    texte: 'La robe de ma fille pour son mariage était magnifique. Fatimata a un vrai talent !',
    note: 5,
    auteurId: 'cit-2',
    commerceId: 'com-2',
    iaScore: 0.95,
    iaResume: 'Éloge du talent de la couturière pour une robe de mariage.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-05T10:30:00Z',
  },
  {
    id: 'com-3',
    texte: 'Bonne table en bois, mais le délai de livraison était un peu long. 3 semaines au lieu de 2.',
    note: 4,
    auteurId: 'cit-3',
    commerceId: 'com-3',
    iaScore: 0.68,
    iaResume: 'Satisfait du produit mais critique sur le délai de livraison.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-08T16:00:00Z',
  },
  {
    id: 'com-4',
    texte: 'Aminata a soudé ma grille d\'entrée. Solide et bien fini. Prix correct.',
    note: 4,
    auteurId: 'cit-4',
    commerceId: 'com-4',
    iaScore: 0.78,
    iaResume: 'Travail de soudure jugé solide et bien fini. Prix jugé correct.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-10T09:00:00Z',
  },
  {
    id: 'com-5',
    texte: 'Problème résolu rapidement. Moussa est très professionnel. Installation électrique impeccable.',
    note: 5,
    auteurId: 'cit-5',
    commerceId: 'com-5',
    iaScore: 0.89,
    iaResume: 'Client satisfait de la rapidité et du professionnalisme.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-12T11:00:00Z',
  },
  {
    id: 'com-6',
    texte: 'Fuite d\'eau réparée en moins d\'1 heure. Merci Aissatou !',
    note: 5,
    auteurId: 'cit-1',
    commerceId: 'com-6',
    iaScore: 0.91,
    iaResume: 'Intervention rapide pour une fuite d\'eau. Satisfaction totale.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-15T14:00:00Z',
  },
  {
    id: 'com-7',
    texte: 'Super coupe, ambiance sympa. Boubacar connaît son métier. Je suis fidèle depuis 6 mois.',
    note: 5,
    auteurId: 'cit-2',
    commerceId: 'com-7',
    iaScore: 0.93,
    iaResume: 'Client fidèle satisfait de la coupe et de l\'ambiance.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-18T10:00:00Z',
  },
  {
    id: 'com-8',
    texte: 'Écran de mon iPhone remplacé en 30 minutes. Prix un peu élevé mais travail bien fait.',
    note: 4,
    auteurId: 'cit-3',
    commerceId: 'com-8',
    iaScore: 0.72,
    iaResume: 'Réparation rapide mais prix jugé élevé.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-20T15:00:00Z',
  },
  {
    id: 'com-9',
    texte: 'Clim installée dans mon bureau. Fonctionne parfaitement. Amadou est sérieux.',
    note: 4,
    auteurId: 'cit-4',
    commerceId: 'com-9',
    iaScore: 0.81,
    iaResume: 'Installation de climatisation réussie. Professionnalisme reconnu.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-22T09:00:00Z',
  },
  {
    id: 'com-10',
    texte: 'Ma chambre a été repeinte en bleu ciel. Le résultat est superbe. Merci Fatimata !',
    note: 5,
    auteurId: 'cit-5',
    commerceId: 'com-10',
    iaScore: 0.94,
    iaResume: 'Satisfaction totale pour le travail de peinture. Résultat superbe.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-23T11:00:00Z',
  },
  {
    id: 'com-11',
    texte: 'Moussa a réparé ma Peugeot 206. Moteur comme neuf. Prix raisonnable.',
    note: 4,
    auteurId: 'cit-1',
    commerceId: 'com-11',
    iaScore: 0.82,
    iaResume: 'Réparation moteur réussie. Prix jugé raisonnable.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-24T14:00:00Z',
  },
  {
    id: 'com-12',
    texte: 'Costume de mariage parfait. Ibrahim a respecté le design demandé. Très content.',
    note: 5,
    auteurId: 'cit-2',
    commerceId: 'com-12',
    iaScore: 0.96,
    iaResume: 'Costume de mariage parfaitement réalisé selon le design demandé.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-25T10:00:00Z',
  },
  {
    id: 'com-13',
    texte: 'Tresses magnifiques. Aminata est très douée avec les enfants. Mon fils a été sage.',
    note: 5,
    auteurId: 'cit-3',
    commerceId: 'com-13',
    iaScore: 0.90,
    iaResume: 'Coiffure réussie. Compétence reconnue avec les enfants.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-25T15:00:00Z',
  },
  {
    id: 'com-14',
    texte: 'Peinture extérieure de ma maison. Travail propre et soigné. Boubacar est un pro.',
    note: 4,
    auteurId: 'cit-4',
    commerceId: 'com-14',
    iaScore: 0.83,
    iaResume: 'Peinture extérieure réalisée proprement. Professionnalisme reconnu.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-26T09:00:00Z',
  },
  {
    id: 'com-15',
    texte: 'Clim réparée rapidement. Aissatou est fiable et honnête. Je recommande.',
    note: 5,
    auteurId: 'cit-5',
    commerceId: 'com-15',
    iaScore: 0.88,
    iaResume: 'Dépannage climatisation rapide. Fiabilité et honnêteté reconnues.',
    estSpam: false,
    estModer: true,
    dateCreation: '2025-06-26T11:00:00Z',
  },
];

export const mockStatistiques: StatistiquesGlobales = {
  totalUtilisateurs: 13,
  totalCommerces: 15,
  totalCommentaires: 15,
  totalVues: 2048,
  commercesParCategorie: [
    { categorie: 'Mécanicien', nombre: 3 },
    { categorie: 'Couturier', nombre: 2 },
    { categorie: 'Menuisier', nombre: 1 },
    { categorie: 'Soudeur', nombre: 1 },
    { categorie: 'Électricien', nombre: 1 },
    { categorie: 'Plombier', nombre: 1 },
    { categorie: 'Coiffeur', nombre: 2 },
    { categorie: 'Réparateur téléphones', nombre: 1 },
    { categorie: 'Frigoriste', nombre: 1 },
    { categorie: 'Peintre', nombre: 2 },
  ],
  activiteRecente: [
    { date: '2025-06-26', type: 'commentaire', description: 'Nouveau commentaire sur Frigoriste Aissatou Services' },
    { date: '2025-06-26', type: 'commentaire', description: 'Nouveau commentaire sur Peinture Bâtiment Boubacar' },
    { date: '2025-06-25', type: 'commentaire', description: 'Nouveau commentaire sur Coiffure Aminata Beauty' },
    { date: '2025-06-25', type: 'commentaire', description: 'Nouveau commentaire sur Couturier Ibrahim Élégance' },
    { date: '2025-06-24', type: 'commentaire', description: 'Nouveau commentaire sur Mécanicien Moussa Pro' },
    { date: '2025-06-24', type: 'inscription', description: 'Nouvel artisan inscrit : Souderie Aminata' },
    { date: '2025-06-23', type: 'commentaire', description: 'Nouveau commentaire sur Plomberie Aissatou' },
    { date: '2025-06-23', type: 'commentaire', description: 'Nouveau commentaire sur Peinture & Déco Fatimata' },
    { date: '2025-06-22', type: 'commentaire', description: 'Nouveau commentaire sur Froid & Clim Amadou' },
    { date: '2025-06-22', type: 'commentaire', description: 'Nouveau commentaire sur Réparation Phone Rasmata' },
  ],
};

export function getCommercesByCategorie(categorieId: string): Commerce[] {
  return mockCommerces.filter((c) => c.categorieId === categorieId);
}

export function getCommerceById(id: string): Commerce | undefined {
  return mockCommerces.find((c) => c.id === id);
}
